# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fine Tuning a Large Language Model for Socratic Interactions
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Using Large Language Models (LLMs) in education presents unique challenges. Typically, LLMs are designed to provide 
  direct answers to questions, which can hinder students' critical thinking and self-discovery skills. To address this, 
  we focus on fine-tuning LLMs to facilitate Socratic interactions. Instead of giving straightforward answers, these 
  models guide students to explore and find the answers themselves. We achieve this through Direct Preference 
  Optimization (DPO). We test our approach with diverse datasets, including various educational materials and Socratic 
  dialogues. Using advanced models like GPT-4o for evaluation, our results show that DPO successfully fine-tunes LLMs 
  for Socratic dialogue, enhancing their educational value.
baseurl: "/socratic-llm/" # the subpath of your site, e.g. /blog
url: "https://giovannigatti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  GiovanniGatti

destination: docs/

# Build settings
markdown: kramdown
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
